import type { ContactMe } from '../../entities/ContactMe'

// =============================================================================
// IContactWriteRepository
// Write-only interface for ContactMe.
// No read methods — admin reads contact messages via Prisma Studio or future endpoint.
// id excluded from input — generated by database.
// createdAt set server-side — never trusted from client.
// =============================================================================
export interface IContactWriteRepository {
  save(data: Omit<ContactMe, 'id'>): Promise<ContactMe>
}