import type { ContactMe } from '../../entities/ContactMe'

// =============================================================================
// IContactWriteRepository
// Write interface for ContactMe aggregate.
// Separated from IContactReadRepository per Interface Segregation Principle.
// id excluded from save input — generated by database.
// createdAt set server-side — never trusted from client.
// =============================================================================
export interface IContactWriteRepository {
    /** Persists a new contact form submission */
    save(data: Omit<ContactMe, 'id'>): Promise<ContactMe>

    /**
     * Deletes a contact message by PK.
     * Returns true if deleted, false if no row with that id was found.
     * Caller decides whether to throw NotFoundError (DeleteContactMessageCommand does).
     */
    delete(id: number): Promise<boolean>
}